- name: Set subnet inside virbr
  vars:
    vlan_to_octet_map:
      80: 0
      81: 1
      82: 2
      83: 3
      84: 4
      85: 5
      86: 6
      87: 7
      88: 8
  set_fact:
    subnet: "{{ vlan_to_octet_map[virbr | int] }}"

- name: Set ldapbase
  set_fact:
    ldapbase: "dc={{ domain.split('.')[0] }},dc={{ domain.split('.')[1] }},dc={{ domain.split('.')[2] }}"

- name: Set ip
  set_fact:
    ip: "10.8.{{ subnet }}.{{ netsuffix }}"

- name: Set FQDN
  set_fact:
    fqdn: "{{ hostname }}.{{ domain }}"

- name: Set REALM
  set_fact: 
    realm: "{{ domain|upper }}"

- name: Set vm
  set_fact:
    vm_dir: "{{ vms_dir }}/{{ fqdn }}"