- name: Set vm local variables
  set_fact:
    virbr: "80"
    netsuffix: "81" 
    hostname: "worker01"
    rootvg_size: 20
    vcpus: 2
    podnetwork: "10.38.0.0/16"
    svcnetwork: "10.49.0.0/16"
    clusterdom: "cluster.local"
    master: "master01.vxland.syscallx86.com"
    bridge_name: "br-ex"
    iface: "enp1s0"
    ip_address: "10.8.0.81"
    k8s_role: "worker"
